/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_n_admin (void);
GtkWidget* create_n_m_menu (void);
GtkWidget* create_n_afficher_menu (void);
GtkWidget* create_n_supprimer (void);
GtkWidget* create_n_modifier_choix (void);
