/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_n_admin (void)
{
  GtkWidget *n_admin;
  GtkWidget *fixed3;
  GtkWidget *n_m_supprimer;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *n_supprimer_menu;
  GtkWidget *n_menu_afficher;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *hseparator4;
  GtkWidget *vseparator3;
  GtkWidget *n_menu_modifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *vseparator4;
  GtkWidget *n_theme;
  GtkWidget *image31;
  GtkWidget *n_admin_scrolle;
  GtkWidget *viewport1;
  GtkWidget *fixed10;
  GtkWidget *n_theme_1;
  GtkWidget *n_theme_2;
  GtkWidget *n_theme_3;
  GtkWidget *n_theme_4;
  GtkWidget *aide_menu;
  GtkWidget *image24;
  GtkWidget *n_m_ajouter;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label9;
  GtkWidget *meilleur_m_menu;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image29;
  GtkWidget *label205;
  GtkWidget *hseparator5;
  GtkWidget *n_logout_menu;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image14;
  GtkWidget *label14;
  GtkWidget *n_m_meilleur;
  GtkWidget *bienvenue;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  n_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (n_admin), _("Espace Admin"));
  gtk_window_set_position (GTK_WINDOW (n_admin), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_default_size (GTK_WINDOW (n_admin), 500, 500);
  gtk_window_set_resizable (GTK_WINDOW (n_admin), FALSE);
  gtk_window_set_icon_name (GTK_WINDOW (n_admin), "gtk-open");

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (n_admin), fixed3);

  n_m_supprimer = gtk_button_new ();
  gtk_widget_show (n_m_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), n_m_supprimer, 248, 312);
  gtk_widget_set_size_request (n_m_supprimer, 216, 56);
  gtk_tooltips_set_tip (tooltips, n_m_supprimer, _("Taper pour supprimer un Menu"), NULL);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (n_m_supprimer), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  n_supprimer_menu = gtk_label_new_with_mnemonic (_("<span font=\"12\"    foreground=\"#0D1D7A\" >  Supprimer Menu</span>"));
  gtk_widget_show (n_supprimer_menu);
  gtk_box_pack_start (GTK_BOX (hbox9), n_supprimer_menu, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (n_supprimer_menu), TRUE);

  n_menu_afficher = gtk_button_new ();
  gtk_widget_show (n_menu_afficher);
  gtk_fixed_put (GTK_FIXED (fixed3), n_menu_afficher, 248, 248);
  gtk_widget_set_size_request (n_menu_afficher, 216, 56);
  gtk_tooltips_set_tip (tooltips, n_menu_afficher, _("Taper pour afficher un Menu deja stoker"), NULL);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (n_menu_afficher), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_(" <span font=\"12\"    foreground=\"#0D1D7A\" > Afficher Menu</span>"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator4, 0, 504);
  gtk_widget_set_size_request (hseparator4, 728, 16);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_show (vseparator3);
  gtk_fixed_put (GTK_FIXED (fixed3), vseparator3, 0, 0);
  gtk_widget_set_size_request (vseparator3, 24, 520);

  n_menu_modifier = gtk_button_new ();
  gtk_widget_show (n_menu_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), n_menu_modifier, 248, 120);
  gtk_widget_set_size_request (n_menu_modifier, 216, 56);
  gtk_tooltips_set_tip (tooltips, n_menu_modifier, _("Taper pour ajouter un Menu"), NULL);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (n_menu_modifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_(" <span font=\"12\"    foreground=\"#0D1D7A\" > Ajouter Choix</span>"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  vseparator4 = gtk_vseparator_new ();
  gtk_widget_show (vseparator4);
  gtk_fixed_put (GTK_FIXED (fixed3), vseparator4, 712, 0);
  gtk_widget_set_size_request (vseparator4, 32, 520);

  n_theme = gtk_button_new ();
  gtk_widget_show (n_theme);
  gtk_fixed_put (GTK_FIXED (fixed3), n_theme, 608, 72);
  gtk_widget_set_size_request (n_theme, 56, 48);
  gtk_button_set_relief (GTK_BUTTON (n_theme), GTK_RELIEF_NONE);

  image31 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_DND);
  gtk_widget_show (image31);
  gtk_container_add (GTK_CONTAINER (n_theme), image31);

  n_admin_scrolle = gtk_scrolled_window_new (NULL, NULL);
  gtk_fixed_put (GTK_FIXED (fixed3), n_admin_scrolle, 472, 96);
  gtk_widget_set_size_request (n_admin_scrolle, 168, 120);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (n_admin_scrolle), viewport1);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed10);

  n_theme_1 = gtk_check_button_new_with_mnemonic (_("image 1"));
  gtk_widget_show (n_theme_1);
  gtk_fixed_put (GTK_FIXED (fixed10), n_theme_1, 24, 0);
  gtk_widget_set_size_request (n_theme_1, 118, 24);

  n_theme_2 = gtk_check_button_new_with_mnemonic (_("image 2"));
  gtk_widget_show (n_theme_2);
  gtk_fixed_put (GTK_FIXED (fixed10), n_theme_2, 24, 24);
  gtk_widget_set_size_request (n_theme_2, 118, 24);

  n_theme_3 = gtk_check_button_new_with_mnemonic (_("image 3"));
  gtk_widget_show (n_theme_3);
  gtk_fixed_put (GTK_FIXED (fixed10), n_theme_3, 24, 48);
  gtk_widget_set_size_request (n_theme_3, 118, 24);

  n_theme_4 = gtk_check_button_new_with_mnemonic (_("image 4"));
  gtk_widget_show (n_theme_4);
  gtk_fixed_put (GTK_FIXED (fixed10), n_theme_4, 24, 72);
  gtk_widget_set_size_request (n_theme_4, 118, 24);

  aide_menu = gtk_button_new ();
  gtk_widget_show (aide_menu);
  gtk_fixed_put (GTK_FIXED (fixed3), aide_menu, 64, 408);
  gtk_widget_set_size_request (aide_menu, 48, 48);
  gtk_tooltips_set_tip (tooltips, aide_menu, _("Bonjour Mr,Madame,\nVous trouverez dans cette application des outils utiles pour vous faciliter votre mission.\nIl suffit de cliquer sur la tache d\303\251sir\303\251 et remplir quelques champs pour vous rendre ce que vous avez besoin de connaitre.\nBienvenue et bon travail."), NULL);
  gtk_button_set_relief (GTK_BUTTON (aide_menu), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (aide_menu), FALSE);

  image24 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_DND);
  gtk_widget_show (image24);
  gtk_container_add (GTK_CONTAINER (aide_menu), image24);
  GTK_WIDGET_SET_FLAGS (image24, GTK_CAN_FOCUS);

  n_m_ajouter = gtk_button_new ();
  gtk_widget_show (n_m_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed3), n_m_ajouter, 248, 184);
  gtk_widget_set_size_request (n_m_ajouter, 216, 56);
  gtk_tooltips_set_tip (tooltips, n_m_ajouter, _("Taper pour modifier un Menu"), NULL);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (n_m_ajouter), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("<span font=\"12\"    foreground=\"#0D1D7A\" > Modifier Choix</span>"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox5), label9, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  meilleur_m_menu = gtk_button_new ();
  gtk_widget_show (meilleur_m_menu);
  gtk_fixed_put (GTK_FIXED (fixed3), meilleur_m_menu, 246, 379);
  gtk_widget_set_size_request (meilleur_m_menu, 216, 56);
  gtk_tooltips_set_tip (tooltips, meilleur_m_menu, _("Taper pour supprimer un Menu"), NULL);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (meilleur_m_menu), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image29 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox19), image29, FALSE, FALSE, 0);

  label205 = gtk_label_new_with_mnemonic (_("<span font=\"12\"    foreground=\"#0D1D7A\" >  Meilleur menu</span>"));
  gtk_widget_show (label205);
  gtk_box_pack_start (GTK_BOX (hbox19), label205, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label205), TRUE);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator5, 0, 0);
  gtk_widget_set_size_request (hseparator5, 744, 16);

  n_logout_menu = gtk_button_new ();
  gtk_widget_show (n_logout_menu);
  gtk_fixed_put (GTK_FIXED (fixed3), n_logout_menu, 72, 72);
  gtk_widget_set_size_request (n_logout_menu, 96, 32);
  gtk_button_set_relief (GTK_BUTTON (n_logout_menu), GTK_RELIEF_HALF);
  gtk_button_set_focus_on_click (GTK_BUTTON (n_logout_menu), FALSE);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (n_logout_menu), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image14 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox10), image14, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("<span  foreground=\" black\" >Logout</span>"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox10), label14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  n_m_meilleur = gtk_label_new ("");
  gtk_widget_show (n_m_meilleur);
  gtk_fixed_put (GTK_FIXED (fixed3), n_m_meilleur, 80, 440);
  gtk_widget_set_size_request (n_m_meilleur, 592, 56);

  bienvenue = gtk_label_new (_("<span font=\"25\"   weight=\"bold\"  foreground=\"#C4DAFF\" >Bienvenue Ch\303\251f</span>\n"));
  gtk_widget_show (bienvenue);
  gtk_fixed_put (GTK_FIXED (fixed3), bienvenue, 184, 72);
  gtk_widget_set_size_request (bienvenue, 360, 56);
  gtk_label_set_use_markup (GTK_LABEL (bienvenue), TRUE);

  g_signal_connect ((gpointer) n_m_supprimer, "clicked",
                    G_CALLBACK (on_n_m_supprimer_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_m_supprimer, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin));
  g_signal_connect ((gpointer) n_menu_afficher, "clicked",
                    G_CALLBACK (on_n_menu_afficher_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_menu_afficher, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin));
  g_signal_connect ((gpointer) n_menu_modifier, "clicked",
                    G_CALLBACK (on_n_menu_modifier_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_menu_modifier, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin));
  g_signal_connect_swapped ((gpointer) n_theme, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (n_admin_scrolle));
  g_signal_connect ((gpointer) n_theme, "clicked",
                    G_CALLBACK (on_n_theme_clicked),
                    NULL);
  g_signal_connect ((gpointer) n_theme_1, "toggled",
                    G_CALLBACK (on_n_theme_1_toggled),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_theme_1, "toggled",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin_scrolle));
  g_signal_connect_swapped ((gpointer) n_theme_1, "toggled",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin));
  g_signal_connect ((gpointer) n_theme_2, "toggled",
                    G_CALLBACK (on_n_theme_2_toggled),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_theme_2, "toggled",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin_scrolle));
  g_signal_connect_swapped ((gpointer) n_theme_2, "toggled",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin));
  g_signal_connect ((gpointer) n_theme_3, "toggled",
                    G_CALLBACK (on_n_theme_3_toggled),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_theme_3, "toggled",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin_scrolle));
  g_signal_connect_swapped ((gpointer) n_theme_3, "toggled",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin));
  g_signal_connect ((gpointer) n_theme_4, "toggled",
                    G_CALLBACK (on_n_theme_4_toggled),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_theme_4, "toggled",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin_scrolle));
  g_signal_connect_swapped ((gpointer) n_theme_4, "toggled",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin));
  g_signal_connect ((gpointer) n_m_ajouter, "clicked",
                    G_CALLBACK (on_n_m_ajouter_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_m_ajouter, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin));
  g_signal_connect ((gpointer) meilleur_m_menu, "clicked",
                    G_CALLBACK (on_meilleur_m_menu_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_logout_menu, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_admin));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (n_admin, n_admin, "n_admin");
  GLADE_HOOKUP_OBJECT (n_admin, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (n_admin, n_m_supprimer, "n_m_supprimer");
  GLADE_HOOKUP_OBJECT (n_admin, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (n_admin, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (n_admin, image9, "image9");
  GLADE_HOOKUP_OBJECT (n_admin, n_supprimer_menu, "n_supprimer_menu");
  GLADE_HOOKUP_OBJECT (n_admin, n_menu_afficher, "n_menu_afficher");
  GLADE_HOOKUP_OBJECT (n_admin, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (n_admin, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (n_admin, image4, "image4");
  GLADE_HOOKUP_OBJECT (n_admin, label5, "label5");
  GLADE_HOOKUP_OBJECT (n_admin, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (n_admin, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (n_admin, n_menu_modifier, "n_menu_modifier");
  GLADE_HOOKUP_OBJECT (n_admin, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (n_admin, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (n_admin, image3, "image3");
  GLADE_HOOKUP_OBJECT (n_admin, label4, "label4");
  GLADE_HOOKUP_OBJECT (n_admin, vseparator4, "vseparator4");
  GLADE_HOOKUP_OBJECT (n_admin, n_theme, "n_theme");
  GLADE_HOOKUP_OBJECT (n_admin, image31, "image31");
  GLADE_HOOKUP_OBJECT (n_admin, n_admin_scrolle, "n_admin_scrolle");
  GLADE_HOOKUP_OBJECT (n_admin, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (n_admin, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (n_admin, n_theme_1, "n_theme_1");
  GLADE_HOOKUP_OBJECT (n_admin, n_theme_2, "n_theme_2");
  GLADE_HOOKUP_OBJECT (n_admin, n_theme_3, "n_theme_3");
  GLADE_HOOKUP_OBJECT (n_admin, n_theme_4, "n_theme_4");
  GLADE_HOOKUP_OBJECT (n_admin, aide_menu, "aide_menu");
  GLADE_HOOKUP_OBJECT (n_admin, image24, "image24");
  GLADE_HOOKUP_OBJECT (n_admin, n_m_ajouter, "n_m_ajouter");
  GLADE_HOOKUP_OBJECT (n_admin, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (n_admin, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (n_admin, image5, "image5");
  GLADE_HOOKUP_OBJECT (n_admin, label9, "label9");
  GLADE_HOOKUP_OBJECT (n_admin, meilleur_m_menu, "meilleur_m_menu");
  GLADE_HOOKUP_OBJECT (n_admin, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (n_admin, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (n_admin, image29, "image29");
  GLADE_HOOKUP_OBJECT (n_admin, label205, "label205");
  GLADE_HOOKUP_OBJECT (n_admin, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (n_admin, n_logout_menu, "n_logout_menu");
  GLADE_HOOKUP_OBJECT (n_admin, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (n_admin, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (n_admin, image14, "image14");
  GLADE_HOOKUP_OBJECT (n_admin, label14, "label14");
  GLADE_HOOKUP_OBJECT (n_admin, n_m_meilleur, "n_m_meilleur");
  GLADE_HOOKUP_OBJECT (n_admin, bienvenue, "bienvenue");
  GLADE_HOOKUP_OBJECT_NO_REF (n_admin, tooltips, "tooltips");

  return n_admin;
}

GtkWidget*
create_n_m_menu (void)
{
  GtkWidget *n_m_menu;
  GtkWidget *rolette;
  GtkWidget *n_entry1_1;
  GtkWidget *n_entry1_2;
  GtkWidget *n_entry1_3;
  GtkWidget *n_entry2_1;
  GtkWidget *n_entry2_2;
  GtkWidget *n_entry2_3;
  GtkWidget *n_entry3_1;
  GtkWidget *n_entry3_2;
  GtkWidget *n_entry3_3;
  GtkWidget *hseparator10;
  GtkWidget *error_remp_menu;
  GtkObject *n_m_sem_spin_adj;
  GtkWidget *n_m_sem_spin;
  GtkWidget *n_jour;
  GtkWidget *n_sem_label;
  GtkWidget *n_com_jours;
  GtkWidget *return_menu;
  GtkWidget *image13;
  GtkWidget *n_repas3_2;
  GtkWidget *n_repas3_3;
  GtkWidget *n_repas3_1;
  GtkWidget *vseparator2;
  GtkWidget *n_repas2_1;
  GtkWidget *n_repas2_2;
  GtkWidget *n_repas2_3;
  GtkWidget *vseparator1;
  GtkWidget *hseparator1;
  GtkWidget *n_repas1_3;
  GtkWidget *n_repas1_2;
  GtkWidget *n_repas1_1;
  GtkWidget *n_diner;
  GtkWidget *n_dej;
  GtkWidget *hseparator3;
  GtkWidget *n_petitdej;
  GtkWidget *n_menu_actualiser;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image16;
  GtkWidget *label18;
  GtkWidget *m_miseajour;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label10;
  GtkWidget *hseparator2;

  n_m_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (n_m_menu), _("Menu de modification"));
  gtk_window_set_position (GTK_WINDOW (n_m_menu), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_resizable (GTK_WINDOW (n_m_menu), FALSE);
  gtk_window_set_icon_name (GTK_WINDOW (n_m_menu), "gtk-new");

  rolette = gtk_fixed_new ();
  gtk_widget_show (rolette);
  gtk_container_add (GTK_CONTAINER (n_m_menu), rolette);
  gtk_container_set_border_width (GTK_CONTAINER (rolette), 4);

  n_entry1_1 = gtk_entry_new ();
  gtk_widget_show (n_entry1_1);
  gtk_fixed_put (GTK_FIXED (rolette), n_entry1_1, 176, 104);
  gtk_widget_set_size_request (n_entry1_1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_entry1_1), 8226);

  n_entry1_2 = gtk_entry_new ();
  gtk_widget_show (n_entry1_2);
  gtk_fixed_put (GTK_FIXED (rolette), n_entry1_2, 176, 144);
  gtk_widget_set_size_request (n_entry1_2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_entry1_2), 8226);

  n_entry1_3 = gtk_entry_new ();
  gtk_widget_show (n_entry1_3);
  gtk_fixed_put (GTK_FIXED (rolette), n_entry1_3, 176, 184);
  gtk_widget_set_size_request (n_entry1_3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_entry1_3), 8226);

  n_entry2_1 = gtk_entry_new ();
  gtk_widget_show (n_entry2_1);
  gtk_fixed_put (GTK_FIXED (rolette), n_entry2_1, 488, 104);
  gtk_widget_set_size_request (n_entry2_1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_entry2_1), 8226);

  n_entry2_2 = gtk_entry_new ();
  gtk_widget_show (n_entry2_2);
  gtk_fixed_put (GTK_FIXED (rolette), n_entry2_2, 488, 144);
  gtk_widget_set_size_request (n_entry2_2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_entry2_2), 8226);

  n_entry2_3 = gtk_entry_new ();
  gtk_widget_show (n_entry2_3);
  gtk_fixed_put (GTK_FIXED (rolette), n_entry2_3, 488, 184);
  gtk_widget_set_size_request (n_entry2_3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_entry2_3), 8226);

  n_entry3_1 = gtk_entry_new ();
  gtk_widget_show (n_entry3_1);
  gtk_fixed_put (GTK_FIXED (rolette), n_entry3_1, 792, 104);
  gtk_widget_set_size_request (n_entry3_1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_entry3_1), 8226);

  n_entry3_2 = gtk_entry_new ();
  gtk_widget_show (n_entry3_2);
  gtk_fixed_put (GTK_FIXED (rolette), n_entry3_2, 792, 144);
  gtk_widget_set_size_request (n_entry3_2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_entry3_2), 8226);

  n_entry3_3 = gtk_entry_new ();
  gtk_widget_show (n_entry3_3);
  gtk_fixed_put (GTK_FIXED (rolette), n_entry3_3, 792, 184);
  gtk_widget_set_size_request (n_entry3_3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (n_entry3_3), 8226);

  hseparator10 = gtk_hseparator_new ();
  gtk_widget_show (hseparator10);
  gtk_fixed_put (GTK_FIXED (rolette), hseparator10, 0, 312);
  gtk_widget_set_size_request (hseparator10, 976, 16);

  error_remp_menu = gtk_label_new ("");
  gtk_widget_show (error_remp_menu);
  gtk_fixed_put (GTK_FIXED (rolette), error_remp_menu, 344, 240);
  gtk_widget_set_size_request (error_remp_menu, 280, 16);

  n_m_sem_spin_adj = gtk_adjustment_new (1, 1, 4, 1, 10, 10);
  n_m_sem_spin = gtk_spin_button_new (GTK_ADJUSTMENT (n_m_sem_spin_adj), 1, 0);
  gtk_widget_show (n_m_sem_spin);
  gtk_fixed_put (GTK_FIXED (rolette), n_m_sem_spin, 624, 19);
  gtk_widget_set_size_request (n_m_sem_spin, 60, 27);

  n_jour = gtk_label_new (_("Jour  :"));
  gtk_widget_show (n_jour);
  gtk_fixed_put (GTK_FIXED (rolette), n_jour, 240, 22);
  gtk_widget_set_size_request (n_jour, 41, 17);

  n_sem_label = gtk_label_new (_("semaine :"));
  gtk_widget_show (n_sem_label);
  gtk_fixed_put (GTK_FIXED (rolette), n_sem_label, 552, 22);
  gtk_widget_set_size_request (n_sem_label, 69, 21);

  n_com_jours = gtk_combo_box_entry_new_text ();
  gtk_widget_show (n_com_jours);
  gtk_fixed_put (GTK_FIXED (rolette), n_com_jours, 288, 16);
  gtk_widget_set_size_request (n_com_jours, 189, 29);
  gtk_container_set_border_width (GTK_CONTAINER (n_com_jours), 7);
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_com_jours), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_com_jours), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_com_jours), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_com_jours), _("jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_com_jours), _("vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_com_jours), _("samedi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_com_jours), _("dimanche"));

  return_menu = gtk_button_new ();
  gtk_widget_show (return_menu);
  gtk_fixed_put (GTK_FIXED (rolette), return_menu, 24, 16);
  gtk_widget_set_size_request (return_menu, 32, 27);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_container_add (GTK_CONTAINER (return_menu), image13);

  n_repas3_2 = gtk_label_new (_("plat principal :"));
  gtk_widget_show (n_repas3_2);
  gtk_fixed_put (GTK_FIXED (rolette), n_repas3_2, 672, 152);
  gtk_widget_set_size_request (n_repas3_2, 116, 16);

  n_repas3_3 = gtk_label_new (_("dessert :"));
  gtk_widget_show (n_repas3_3);
  gtk_fixed_put (GTK_FIXED (rolette), n_repas3_3, 696, 192);
  gtk_widget_set_size_request (n_repas3_3, 108, 16);

  n_repas3_1 = gtk_label_new (_("entr\303\251e :"));
  gtk_widget_show (n_repas3_1);
  gtk_fixed_put (GTK_FIXED (rolette), n_repas3_1, 712, 112);
  gtk_widget_set_size_request (n_repas3_1, 80, 16);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (rolette), vseparator2, 656, 64);
  gtk_widget_set_size_request (vseparator2, 24, 168);

  n_repas2_1 = gtk_label_new (_("entr\303\251e  :"));
  gtk_widget_show (n_repas2_1);
  gtk_fixed_put (GTK_FIXED (rolette), n_repas2_1, 416, 112);
  gtk_widget_set_size_request (n_repas2_1, 64, 16);

  n_repas2_2 = gtk_label_new (_("plat principal :"));
  gtk_widget_show (n_repas2_2);
  gtk_fixed_put (GTK_FIXED (rolette), n_repas2_2, 368, 152);
  gtk_widget_set_size_request (n_repas2_2, 116, 16);

  n_repas2_3 = gtk_label_new (_("dessert :"));
  gtk_widget_show (n_repas2_3);
  gtk_fixed_put (GTK_FIXED (rolette), n_repas2_3, 416, 192);
  gtk_widget_set_size_request (n_repas2_3, 64, 16);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (rolette), vseparator1, 344, 64);
  gtk_widget_set_size_request (vseparator1, 24, 168);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (rolette), hseparator1, 4, 48);
  gtk_widget_set_size_request (hseparator1, 972, 28);

  n_repas1_3 = gtk_label_new (_("produits concentr\303\251s :"));
  gtk_widget_show (n_repas1_3);
  gtk_fixed_put (GTK_FIXED (rolette), n_repas1_3, 8, 192);
  gtk_widget_set_size_request (n_repas1_3, 156, 16);

  n_repas1_2 = gtk_label_new (_("fruits :"));
  gtk_widget_show (n_repas1_2);
  gtk_fixed_put (GTK_FIXED (rolette), n_repas1_2, 96, 152);
  gtk_widget_set_size_request (n_repas1_2, 72, 16);

  n_repas1_1 = gtk_label_new (_("produits laitiers :"));
  gtk_widget_show (n_repas1_1);
  gtk_fixed_put (GTK_FIXED (rolette), n_repas1_1, 32, 104);
  gtk_widget_set_size_request (n_repas1_1, 132, 28);

  n_diner = gtk_label_new (_("d\303\256ner"));
  gtk_widget_show (n_diner);
  gtk_fixed_put (GTK_FIXED (rolette), n_diner, 792, 72);
  gtk_widget_set_size_request (n_diner, 41, 17);

  n_dej = gtk_label_new (_("d\303\251jeuner"));
  gtk_widget_show (n_dej);
  gtk_fixed_put (GTK_FIXED (rolette), n_dej, 440, 72);
  gtk_widget_set_size_request (n_dej, 144, 16);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (rolette), hseparator3, 0, 80);
  gtk_widget_set_size_request (hseparator3, 976, 32);

  n_petitdej = gtk_label_new (_("petit-d\303\251jeuner"));
  gtk_widget_show (n_petitdej);
  gtk_fixed_put (GTK_FIXED (rolette), n_petitdej, 136, 72);
  gtk_widget_set_size_request (n_petitdej, 136, 16);

  n_menu_actualiser = gtk_button_new ();
  gtk_widget_show (n_menu_actualiser);
  gtk_fixed_put (GTK_FIXED (rolette), n_menu_actualiser, 536, 256);
  gtk_widget_set_size_request (n_menu_actualiser, 130, 44);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (n_menu_actualiser), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image16 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox12), image16, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox12), label18, FALSE, FALSE, 0);

  m_miseajour = gtk_button_new ();
  gtk_widget_show (m_miseajour);
  gtk_fixed_put (GTK_FIXED (rolette), m_miseajour, 368, 256);
  gtk_widget_set_size_request (m_miseajour, 128, 45);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (m_miseajour), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_(" Mise a jour"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox6), label10, FALSE, FALSE, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (rolette), hseparator2, 4, 216);
  gtk_widget_set_size_request (hseparator2, 964, 32);

  g_signal_connect ((gpointer) return_menu, "clicked",
                    G_CALLBACK (on_return_menu_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) return_menu, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_m_menu));
  g_signal_connect ((gpointer) n_menu_actualiser, "clicked",
                    G_CALLBACK (on_n_menu_actualiser_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_menu_actualiser, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_m_menu));
  g_signal_connect ((gpointer) m_miseajour, "clicked",
                    G_CALLBACK (on_m_miseajour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (n_m_menu, n_m_menu, "n_m_menu");
  GLADE_HOOKUP_OBJECT (n_m_menu, rolette, "rolette");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_entry1_1, "n_entry1_1");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_entry1_2, "n_entry1_2");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_entry1_3, "n_entry1_3");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_entry2_1, "n_entry2_1");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_entry2_2, "n_entry2_2");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_entry2_3, "n_entry2_3");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_entry3_1, "n_entry3_1");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_entry3_2, "n_entry3_2");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_entry3_3, "n_entry3_3");
  GLADE_HOOKUP_OBJECT (n_m_menu, hseparator10, "hseparator10");
  GLADE_HOOKUP_OBJECT (n_m_menu, error_remp_menu, "error_remp_menu");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_m_sem_spin, "n_m_sem_spin");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_jour, "n_jour");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_sem_label, "n_sem_label");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_com_jours, "n_com_jours");
  GLADE_HOOKUP_OBJECT (n_m_menu, return_menu, "return_menu");
  GLADE_HOOKUP_OBJECT (n_m_menu, image13, "image13");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_repas3_2, "n_repas3_2");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_repas3_3, "n_repas3_3");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_repas3_1, "n_repas3_1");
  GLADE_HOOKUP_OBJECT (n_m_menu, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_repas2_1, "n_repas2_1");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_repas2_2, "n_repas2_2");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_repas2_3, "n_repas2_3");
  GLADE_HOOKUP_OBJECT (n_m_menu, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (n_m_menu, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_repas1_3, "n_repas1_3");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_repas1_2, "n_repas1_2");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_repas1_1, "n_repas1_1");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_diner, "n_diner");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_dej, "n_dej");
  GLADE_HOOKUP_OBJECT (n_m_menu, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_petitdej, "n_petitdej");
  GLADE_HOOKUP_OBJECT (n_m_menu, n_menu_actualiser, "n_menu_actualiser");
  GLADE_HOOKUP_OBJECT (n_m_menu, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (n_m_menu, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (n_m_menu, image16, "image16");
  GLADE_HOOKUP_OBJECT (n_m_menu, label18, "label18");
  GLADE_HOOKUP_OBJECT (n_m_menu, m_miseajour, "m_miseajour");
  GLADE_HOOKUP_OBJECT (n_m_menu, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (n_m_menu, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (n_m_menu, image6, "image6");
  GLADE_HOOKUP_OBJECT (n_m_menu, label10, "label10");
  GLADE_HOOKUP_OBJECT (n_m_menu, hseparator2, "hseparator2");

  return n_m_menu;
}

GtkWidget*
create_n_afficher_menu (void)
{
  GtkWidget *n_afficher_menu;
  GtkWidget *fixed7;
  GtkObject *s_r_adj;
  GtkWidget *s_r;
  GtkWidget *return_aff;
  GtkWidget *image27;
  GtkWidget *rechercher_menu_button;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image25;
  GtkWidget *label28;
  GtkWidget *afficher_tout;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image26;
  GtkWidget *label31;
  GtkWidget *n_aff_clear;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image30;
  GtkWidget *label206;
  GtkWidget *j_r;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *vseparator13;
  GtkWidget *vseparator14;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;

  n_afficher_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (n_afficher_menu), _("Affichage de Menu"));
  gtk_window_set_position (GTK_WINDOW (n_afficher_menu), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_default_size (GTK_WINDOW (n_afficher_menu), 900, 300);
  gtk_window_set_resizable (GTK_WINDOW (n_afficher_menu), FALSE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (n_afficher_menu), fixed7);

  s_r_adj = gtk_adjustment_new (1, 1, 4, 1, 10, 10);
  s_r = gtk_spin_button_new (GTK_ADJUSTMENT (s_r_adj), 1, 0);
  gtk_widget_show (s_r);
  gtk_fixed_put (GTK_FIXED (fixed7), s_r, 216, 104);
  gtk_widget_set_size_request (s_r, 64, 32);

  return_aff = gtk_button_new ();
  gtk_widget_show (return_aff);
  gtk_fixed_put (GTK_FIXED (fixed7), return_aff, 32, 24);
  gtk_widget_set_size_request (return_aff, 32, 27);

  image27 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_container_add (GTK_CONTAINER (return_aff), image27);

  rechercher_menu_button = gtk_button_new ();
  gtk_widget_show (rechercher_menu_button);
  gtk_fixed_put (GTK_FIXED (fixed7), rechercher_menu_button, 72, 184);
  gtk_widget_set_size_request (rechercher_menu_button, 168, 80);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (rechercher_menu_button), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image25 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox17), image25, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("  Rechercher"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox17), label28, FALSE, FALSE, 0);

  afficher_tout = gtk_button_new ();
  gtk_widget_show (afficher_tout);
  gtk_fixed_put (GTK_FIXED (fixed7), afficher_tout, 72, 280);
  gtk_widget_set_size_request (afficher_tout, 168, 80);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (afficher_tout), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image26 = gtk_image_new_from_stock ("gtk-paste", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox18), image26, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_(" Afficher tout"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox18), label31, FALSE, FALSE, 0);

  n_aff_clear = gtk_button_new ();
  gtk_widget_show (n_aff_clear);
  gtk_fixed_put (GTK_FIXED (fixed7), n_aff_clear, 72, 376);
  gtk_widget_set_size_request (n_aff_clear, 168, 80);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (n_aff_clear), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image30 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox20), image30, FALSE, FALSE, 0);

  label206 = gtk_label_new_with_mnemonic (_(" Efasser tout"));
  gtk_widget_show (label206);
  gtk_box_pack_start (GTK_BOX (hbox20), label206, FALSE, FALSE, 0);

  j_r = gtk_combo_box_entry_new_text ();
  gtk_widget_show (j_r);
  gtk_fixed_put (GTK_FIXED (fixed7), j_r, 16, 104);
  gtk_widget_set_size_request (j_r, 168, 32);
  gtk_container_set_border_width (GTK_CONTAINER (j_r), 7);
  gtk_combo_box_append_text (GTK_COMBO_BOX (j_r), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (j_r), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (j_r), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (j_r), _("jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (j_r), _("vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (j_r), _("samedi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (j_r), _("dimanche"));

  label29 = gtk_label_new (_("Jour"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed7), label29, 24, 80);
  gtk_widget_set_size_request (label29, 48, 24);

  label30 = gtk_label_new (_("Semaine"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed7), label30, 216, 80);
  gtk_widget_set_size_request (label30, 64, 24);

  vseparator13 = gtk_vseparator_new ();
  gtk_widget_show (vseparator13);
  gtk_fixed_put (GTK_FIXED (fixed7), vseparator13, 288, 0);
  gtk_widget_set_size_request (vseparator13, 16, 488);

  vseparator14 = gtk_vseparator_new ();
  gtk_widget_show (vseparator14);
  gtk_fixed_put (GTK_FIXED (fixed7), vseparator14, 1168, 0);
  gtk_widget_set_size_request (vseparator14, 16, 488);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed7), scrolledwindow1, 312, 16);
  gtk_widget_set_size_request (scrolledwindow1, 848, 456);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 56, 48);

  g_signal_connect ((gpointer) return_aff, "clicked",
                    G_CALLBACK (on_return_aff_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) return_aff, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_afficher_menu));
  g_signal_connect ((gpointer) rechercher_menu_button, "clicked",
                    G_CALLBACK (on_rechercher_menu_button_clicked),
                    NULL);
  g_signal_connect_data ((gpointer) rechercher_menu_button, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (n_afficher_menu),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect ((gpointer) afficher_tout, "clicked",
                    G_CALLBACK (on_afficher_tout_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) afficher_tout, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_afficher_menu));
  g_signal_connect ((gpointer) n_aff_clear, "clicked",
                    G_CALLBACK (on_n_aff_clear_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) n_aff_clear, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_afficher_menu));
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (n_afficher_menu, n_afficher_menu, "n_afficher_menu");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, s_r, "s_r");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, return_aff, "return_aff");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, image27, "image27");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, rechercher_menu_button, "rechercher_menu_button");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, image25, "image25");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, label28, "label28");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, afficher_tout, "afficher_tout");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, image26, "image26");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, label31, "label31");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, n_aff_clear, "n_aff_clear");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, image30, "image30");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, label206, "label206");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, j_r, "j_r");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, label29, "label29");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, label30, "label30");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, vseparator13, "vseparator13");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, vseparator14, "vseparator14");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (n_afficher_menu, treeview1, "treeview1");

  return n_afficher_menu;
}

GtkWidget*
create_n_supprimer (void)
{
  GtkWidget *n_supprimer;
  GtkWidget *fixed8;
  GtkWidget *n_supp_mardi;
  GSList *n_supp_mardi_group = NULL;
  GtkWidget *n_supp_mercredi;
  GtkWidget *n_supp_jeudi;
  GtkWidget *n_supp_vendredi;
  GtkWidget *n_supp_samedi;
  GtkWidget *n_supp_dimanche;
  GtkWidget *return_sup_menu;
  GtkWidget *image17;
  GtkWidget *label15;
  GtkWidget *n_supp_valider;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image15;
  GtkWidget *label17;
  GtkWidget *n_supp_msg;
  GtkWidget *hseparator19;
  GtkWidget *label16;
  GtkWidget *n_supp_sem;
  GtkWidget *n_supp_lundi;

  n_supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (n_supprimer), _("Supprimer Menu"));
  gtk_window_set_position (GTK_WINDOW (n_supprimer), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_default_size (GTK_WINDOW (n_supprimer), 500, 400);
  gtk_window_set_resizable (GTK_WINDOW (n_supprimer), FALSE);
  gtk_window_set_icon_name (GTK_WINDOW (n_supprimer), "gtk-cancel");

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (n_supprimer), fixed8);

  n_supp_mardi = gtk_radio_button_new_with_mnemonic (NULL, _("Mardi"));
  gtk_widget_show (n_supp_mardi);
  gtk_fixed_put (GTK_FIXED (fixed8), n_supp_mardi, 40, 128);
  gtk_widget_set_size_request (n_supp_mardi, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (n_supp_mardi), n_supp_mardi_group);
  n_supp_mardi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (n_supp_mardi));

  n_supp_mercredi = gtk_radio_button_new_with_mnemonic (NULL, _("Mercredi"));
  gtk_widget_show (n_supp_mercredi);
  gtk_fixed_put (GTK_FIXED (fixed8), n_supp_mercredi, 40, 176);
  gtk_widget_set_size_request (n_supp_mercredi, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (n_supp_mercredi), n_supp_mardi_group);
  n_supp_mardi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (n_supp_mercredi));

  n_supp_jeudi = gtk_radio_button_new_with_mnemonic (NULL, _("Jeudi"));
  gtk_widget_show (n_supp_jeudi);
  gtk_fixed_put (GTK_FIXED (fixed8), n_supp_jeudi, 40, 224);
  gtk_widget_set_size_request (n_supp_jeudi, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (n_supp_jeudi), n_supp_mardi_group);
  n_supp_mardi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (n_supp_jeudi));

  n_supp_vendredi = gtk_radio_button_new_with_mnemonic (NULL, _("Vendredi\n"));
  gtk_widget_show (n_supp_vendredi);
  gtk_fixed_put (GTK_FIXED (fixed8), n_supp_vendredi, 40, 264);
  gtk_widget_set_size_request (n_supp_vendredi, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (n_supp_vendredi), n_supp_mardi_group);
  n_supp_mardi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (n_supp_vendredi));

  n_supp_samedi = gtk_radio_button_new_with_mnemonic (NULL, _("Samedi"));
  gtk_widget_show (n_supp_samedi);
  gtk_fixed_put (GTK_FIXED (fixed8), n_supp_samedi, 40, 312);
  gtk_widget_set_size_request (n_supp_samedi, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (n_supp_samedi), n_supp_mardi_group);
  n_supp_mardi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (n_supp_samedi));

  n_supp_dimanche = gtk_radio_button_new_with_mnemonic (NULL, _("Dimanche"));
  gtk_widget_show (n_supp_dimanche);
  gtk_fixed_put (GTK_FIXED (fixed8), n_supp_dimanche, 40, 352);
  gtk_widget_set_size_request (n_supp_dimanche, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (n_supp_dimanche), n_supp_mardi_group);
  n_supp_mardi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (n_supp_dimanche));

  return_sup_menu = gtk_button_new ();
  gtk_widget_show (return_sup_menu);
  gtk_fixed_put (GTK_FIXED (fixed8), return_sup_menu, 24, 24);
  gtk_widget_set_size_request (return_sup_menu, 32, 27);
  gtk_button_set_relief (GTK_BUTTON (return_sup_menu), GTK_RELIEF_NONE);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (return_sup_menu), image17);

  label15 = gtk_label_new (_("semaine :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed8), label15, 288, 144);
  gtk_widget_set_size_request (label15, 80, 16);

  n_supp_valider = gtk_button_new ();
  gtk_widget_show (n_supp_valider);
  gtk_fixed_put (GTK_FIXED (fixed8), n_supp_valider, 272, 192);
  gtk_widget_set_size_request (n_supp_valider, 176, 56);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (n_supp_valider), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image15 = gtk_image_new_from_stock ("gtk-caps-lock-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox11), image15, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_(" Valider"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox11), label17, FALSE, FALSE, 0);

  n_supp_msg = gtk_label_new ("");
  gtk_widget_show (n_supp_msg);
  gtk_fixed_put (GTK_FIXED (fixed8), n_supp_msg, 208, 264);
  gtk_widget_set_size_request (n_supp_msg, 288, 32);

  hseparator19 = gtk_hseparator_new ();
  gtk_widget_show (hseparator19);
  gtk_fixed_put (GTK_FIXED (fixed8), hseparator19, 0, 384);
  gtk_widget_set_size_request (hseparator19, 496, 24);

  label16 = gtk_label_new (_("supp menu\n"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed8), label16, 72, 16);
  gtk_widget_set_size_request (label16, 320, 48);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  n_supp_sem = gtk_combo_box_new_text ();
  gtk_widget_show (n_supp_sem);
  gtk_fixed_put (GTK_FIXED (fixed8), n_supp_sem, 376, 136);
  gtk_widget_set_size_request (n_supp_sem, 56, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_supp_sem), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_supp_sem), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_supp_sem), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (n_supp_sem), _("4"));

  n_supp_lundi = gtk_radio_button_new_with_mnemonic (NULL, _("Lundi"));
  gtk_widget_show (n_supp_lundi);
  gtk_fixed_put (GTK_FIXED (fixed8), n_supp_lundi, 40, 80);
  gtk_widget_set_size_request (n_supp_lundi, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (n_supp_lundi), n_supp_mardi_group);
  n_supp_mardi_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (n_supp_lundi));

  g_signal_connect ((gpointer) n_supp_mardi, "toggled",
                    G_CALLBACK (on_n_supp_mardi_toggled),
                    NULL);
  g_signal_connect ((gpointer) n_supp_mercredi, "toggled",
                    G_CALLBACK (on_n_supp_mercredi_toggled),
                    NULL);
  g_signal_connect ((gpointer) n_supp_jeudi, "toggled",
                    G_CALLBACK (on_n_supp_jeudi_toggled),
                    NULL);
  g_signal_connect ((gpointer) n_supp_vendredi, "toggled",
                    G_CALLBACK (on_n_supp_vendredi_toggled),
                    NULL);
  g_signal_connect ((gpointer) n_supp_samedi, "toggled",
                    G_CALLBACK (on_n_supp_samedi_toggled),
                    NULL);
  g_signal_connect ((gpointer) n_supp_dimanche, "toggled",
                    G_CALLBACK (on_n_supp_dimanche_toggled),
                    NULL);
  g_signal_connect ((gpointer) return_sup_menu, "clicked",
                    G_CALLBACK (on_return_sup_menu_clicked),
                    NULL);
  g_signal_connect_data ((gpointer) return_sup_menu, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (n_supprimer),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect ((gpointer) n_supp_valider, "clicked",
                    G_CALLBACK (on_n_supp_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) n_supp_sem, "changed",
                    G_CALLBACK (on_n_supp_sem_changed),
                    NULL);
  g_signal_connect ((gpointer) n_supp_lundi, "toggled",
                    G_CALLBACK (on_n_supp_lundi_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (n_supprimer, n_supprimer, "n_supprimer");
  GLADE_HOOKUP_OBJECT (n_supprimer, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (n_supprimer, n_supp_mardi, "n_supp_mardi");
  GLADE_HOOKUP_OBJECT (n_supprimer, n_supp_mercredi, "n_supp_mercredi");
  GLADE_HOOKUP_OBJECT (n_supprimer, n_supp_jeudi, "n_supp_jeudi");
  GLADE_HOOKUP_OBJECT (n_supprimer, n_supp_vendredi, "n_supp_vendredi");
  GLADE_HOOKUP_OBJECT (n_supprimer, n_supp_samedi, "n_supp_samedi");
  GLADE_HOOKUP_OBJECT (n_supprimer, n_supp_dimanche, "n_supp_dimanche");
  GLADE_HOOKUP_OBJECT (n_supprimer, return_sup_menu, "return_sup_menu");
  GLADE_HOOKUP_OBJECT (n_supprimer, image17, "image17");
  GLADE_HOOKUP_OBJECT (n_supprimer, label15, "label15");
  GLADE_HOOKUP_OBJECT (n_supprimer, n_supp_valider, "n_supp_valider");
  GLADE_HOOKUP_OBJECT (n_supprimer, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (n_supprimer, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (n_supprimer, image15, "image15");
  GLADE_HOOKUP_OBJECT (n_supprimer, label17, "label17");
  GLADE_HOOKUP_OBJECT (n_supprimer, n_supp_msg, "n_supp_msg");
  GLADE_HOOKUP_OBJECT (n_supprimer, hseparator19, "hseparator19");
  GLADE_HOOKUP_OBJECT (n_supprimer, label16, "label16");
  GLADE_HOOKUP_OBJECT (n_supprimer, n_supp_sem, "n_supp_sem");
  GLADE_HOOKUP_OBJECT (n_supprimer, n_supp_lundi, "n_supp_lundi");

  return n_supprimer;
}

GtkWidget*
create_n_modifier_choix (void)
{
  GtkWidget *n_modifier_choix;
  GtkWidget *fixed9;
  GtkWidget *modif_pdej;
  GtkWidget *modif_dej;
  GtkWidget *modif_dinner;
  GtkWidget *modif_pdej1;
  GtkWidget *modif_dinner1;
  GtkWidget *modif_pdej2;
  GtkWidget *modif_dinner2;
  GtkWidget *modif_dej1;
  GtkWidget *modif_dej2;
  GtkWidget *checkbutton_dej;
  GtkWidget *checkbutton_dinner;
  GtkWidget *hseparator14;
  GtkWidget *hseparator15;
  GtkWidget *hseparator17;
  GtkWidget *hseparator16;
  GtkWidget *radiobutton_sem1;
  GSList *radiobutton_sem1_group = NULL;
  GtkWidget *radiobutton_sem2;
  GtkWidget *radiobutton_sem3;
  GtkWidget *radiobutton_sem4;
  GtkWidget *checkbutton_pdej;
  GtkWidget *comboboxentry_jour_modifier;
  GtkWidget *hseparator18;
  GtkWidget *modifier_menu;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image19;
  GtkWidget *label23;
  GtkWidget *actualiser_modifier;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image21;
  GtkWidget *label25;
  GtkWidget *return_modifier_choix;
  GtkWidget *image22;
  GtkWidget *modif_remplire_case;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image20;
  GtkWidget *label24;
  GtkWidget *error_modifier_msg;

  n_modifier_choix = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (n_modifier_choix), _("Modification de choix"));
  gtk_window_set_position (GTK_WINDOW (n_modifier_choix), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_resizable (GTK_WINDOW (n_modifier_choix), FALSE);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (n_modifier_choix), fixed9);

  modif_pdej = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), modif_pdej, 200, 176);
  gtk_widget_set_size_request (modif_pdej, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modif_pdej), 8226);

  modif_dej = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), modif_dej, 200, 224);
  gtk_widget_set_size_request (modif_dej, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modif_dej), 8226);

  modif_dinner = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), modif_dinner, 200, 272);
  gtk_widget_set_size_request (modif_dinner, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modif_dinner), 8226);

  modif_pdej1 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), modif_pdej1, 408, 176);
  gtk_widget_set_size_request (modif_pdej1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modif_pdej1), 8226);

  modif_dinner1 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), modif_dinner1, 408, 272);
  gtk_widget_set_size_request (modif_dinner1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modif_dinner1), 8226);

  modif_pdej2 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), modif_pdej2, 608, 176);
  gtk_widget_set_size_request (modif_pdej2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modif_pdej2), 8226);

  modif_dinner2 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), modif_dinner2, 608, 272);
  gtk_widget_set_size_request (modif_dinner2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modif_dinner2), 8226);

  modif_dej1 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), modif_dej1, 408, 224);
  gtk_widget_set_size_request (modif_dej1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modif_dej1), 8226);

  modif_dej2 = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed9), modif_dej2, 608, 224);
  gtk_widget_set_size_request (modif_dej2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modif_dej2), 8226);

  checkbutton_dej = gtk_check_button_new_with_mnemonic (_("Dejeuner"));
  gtk_widget_show (checkbutton_dej);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton_dej, 40, 224);
  gtk_widget_set_size_request (checkbutton_dej, 118, 24);

  checkbutton_dinner = gtk_check_button_new_with_mnemonic (_("Dinner"));
  gtk_widget_show (checkbutton_dinner);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton_dinner, 40, 272);
  gtk_widget_set_size_request (checkbutton_dinner, 118, 24);

  hseparator14 = gtk_hseparator_new ();
  gtk_widget_show (hseparator14);
  gtk_fixed_put (GTK_FIXED (fixed9), hseparator14, 0, 208);
  gtk_widget_set_size_request (hseparator14, 816, 16);

  hseparator15 = gtk_hseparator_new ();
  gtk_widget_show (hseparator15);
  gtk_fixed_put (GTK_FIXED (fixed9), hseparator15, 0, 256);
  gtk_widget_set_size_request (hseparator15, 816, 16);

  hseparator17 = gtk_hseparator_new ();
  gtk_widget_show (hseparator17);
  gtk_fixed_put (GTK_FIXED (fixed9), hseparator17, 0, 152);
  gtk_widget_set_size_request (hseparator17, 816, 16);

  hseparator16 = gtk_hseparator_new ();
  gtk_widget_show (hseparator16);
  gtk_fixed_put (GTK_FIXED (fixed9), hseparator16, 0, 304);
  gtk_widget_set_size_request (hseparator16, 816, 16);

  radiobutton_sem1 = gtk_radio_button_new_with_mnemonic (NULL, _("Semaine 1"));
  gtk_widget_show (radiobutton_sem1);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton_sem1, 256, 96);
  gtk_widget_set_size_request (radiobutton_sem1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_sem1), radiobutton_sem1_group);
  radiobutton_sem1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_sem1));

  radiobutton_sem2 = gtk_radio_button_new_with_mnemonic (NULL, _("Semaine 2"));
  gtk_widget_show (radiobutton_sem2);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton_sem2, 376, 96);
  gtk_widget_set_size_request (radiobutton_sem2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_sem2), radiobutton_sem1_group);
  radiobutton_sem1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_sem2));

  radiobutton_sem3 = gtk_radio_button_new_with_mnemonic (NULL, _("Semaine 3"));
  gtk_widget_show (radiobutton_sem3);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton_sem3, 504, 96);
  gtk_widget_set_size_request (radiobutton_sem3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_sem3), radiobutton_sem1_group);
  radiobutton_sem1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_sem3));

  radiobutton_sem4 = gtk_radio_button_new_with_mnemonic (NULL, _("Semaine 4"));
  gtk_widget_show (radiobutton_sem4);
  gtk_fixed_put (GTK_FIXED (fixed9), radiobutton_sem4, 632, 96);
  gtk_widget_set_size_request (radiobutton_sem4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_sem4), radiobutton_sem1_group);
  radiobutton_sem1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_sem4));

  checkbutton_pdej = gtk_check_button_new_with_mnemonic (_("Petit-dejeuner"));
  gtk_widget_show (checkbutton_pdej);
  gtk_fixed_put (GTK_FIXED (fixed9), checkbutton_pdej, 40, 176);
  gtk_widget_set_size_request (checkbutton_pdej, 136, 24);

  comboboxentry_jour_modifier = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry_jour_modifier);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry_jour_modifier, 32, 96);
  gtk_widget_set_size_request (comboboxentry_jour_modifier, 176, 32);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxentry_jour_modifier), 7);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_jour_modifier), _("lundi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_jour_modifier), _("mardi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_jour_modifier), _("mercredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_jour_modifier), _("jeudi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_jour_modifier), _("vendredi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_jour_modifier), _("samedi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry_jour_modifier), _("dimanche"));

  hseparator18 = gtk_hseparator_new ();
  gtk_widget_show (hseparator18);
  gtk_fixed_put (GTK_FIXED (fixed9), hseparator18, 0, 416);
  gtk_widget_set_size_request (hseparator18, 816, 16);

  modifier_menu = gtk_button_new ();
  gtk_widget_show (modifier_menu);
  gtk_fixed_put (GTK_FIXED (fixed9), modifier_menu, 144, 344);
  gtk_widget_set_size_request (modifier_menu, 160, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (modifier_menu), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image19 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox14), image19, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_(" Sauvgarder"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox14), label23, FALSE, FALSE, 0);

  actualiser_modifier = gtk_button_new ();
  gtk_widget_show (actualiser_modifier);
  gtk_fixed_put (GTK_FIXED (fixed9), actualiser_modifier, 552, 344);
  gtk_widget_set_size_request (actualiser_modifier, 176, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (actualiser_modifier), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image21 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox16), image21, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox16), label25, FALSE, FALSE, 0);

  return_modifier_choix = gtk_button_new ();
  gtk_widget_show (return_modifier_choix);
  gtk_fixed_put (GTK_FIXED (fixed9), return_modifier_choix, 24, 24);
  gtk_widget_set_size_request (return_modifier_choix, 32, 27);
  gtk_button_set_relief (GTK_BUTTON (return_modifier_choix), GTK_RELIEF_NONE);

  image22 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_container_add (GTK_CONTAINER (return_modifier_choix), image22);

  modif_remplire_case = gtk_button_new ();
  gtk_widget_show (modif_remplire_case);
  gtk_fixed_put (GTK_FIXED (fixed9), modif_remplire_case, 352, 344);
  gtk_widget_set_size_request (modif_remplire_case, 160, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (modif_remplire_case), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image20 = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox15), image20, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_(" Remplire les case"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox15), label24, FALSE, FALSE, 0);

  error_modifier_msg = gtk_label_new ("");
  gtk_widget_show (error_modifier_msg);
  gtk_fixed_put (GTK_FIXED (fixed9), error_modifier_msg, 240, 320);
  gtk_widget_set_size_request (error_modifier_msg, 360, 24);

  g_signal_connect_swapped ((gpointer) checkbutton_dej, "toggled",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (modif_dej));
  g_signal_connect_swapped ((gpointer) checkbutton_dej, "toggled",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (modif_dej1));
  g_signal_connect_swapped ((gpointer) checkbutton_dej, "toggled",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (modif_dej2));
  g_signal_connect_swapped ((gpointer) checkbutton_dinner, "toggled",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (modif_dinner));
  g_signal_connect_swapped ((gpointer) checkbutton_dinner, "toggled",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (modif_dinner1));
  g_signal_connect_swapped ((gpointer) checkbutton_dinner, "toggled",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (modif_dinner2));
  g_signal_connect ((gpointer) radiobutton_sem1, "toggled",
                    G_CALLBACK (on_radiobutton_sem1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_sem2, "toggled",
                    G_CALLBACK (on_radiobutton_sem2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_sem3, "toggled",
                    G_CALLBACK (on_radiobutton_sem3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_sem4, "toggled",
                    G_CALLBACK (on_radiobutton_sem4_toggled),
                    NULL);
  g_signal_connect_swapped ((gpointer) checkbutton_pdej, "toggled",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (modif_pdej));
  g_signal_connect_swapped ((gpointer) checkbutton_pdej, "toggled",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (modif_pdej1));
  g_signal_connect_swapped ((gpointer) checkbutton_pdej, "toggled",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (modif_pdej2));
  g_signal_connect ((gpointer) modifier_menu, "clicked",
                    G_CALLBACK (on_modifier_menu_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiser_modifier, "clicked",
                    G_CALLBACK (on_actualiser_modifier_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) actualiser_modifier, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_modifier_choix));
  g_signal_connect ((gpointer) return_modifier_choix, "clicked",
                    G_CALLBACK (on_return_modifier_choix_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) return_modifier_choix, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (n_modifier_choix));
  g_signal_connect ((gpointer) modif_remplire_case, "clicked",
                    G_CALLBACK (on_modif_remplire_case_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (n_modifier_choix, n_modifier_choix, "n_modifier_choix");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modif_pdej, "modif_pdej");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modif_dej, "modif_dej");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modif_dinner, "modif_dinner");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modif_pdej1, "modif_pdej1");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modif_dinner1, "modif_dinner1");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modif_pdej2, "modif_pdej2");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modif_dinner2, "modif_dinner2");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modif_dej1, "modif_dej1");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modif_dej2, "modif_dej2");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, checkbutton_dej, "checkbutton_dej");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, checkbutton_dinner, "checkbutton_dinner");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, hseparator14, "hseparator14");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, hseparator15, "hseparator15");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, hseparator17, "hseparator17");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, hseparator16, "hseparator16");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, radiobutton_sem1, "radiobutton_sem1");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, radiobutton_sem2, "radiobutton_sem2");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, radiobutton_sem3, "radiobutton_sem3");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, radiobutton_sem4, "radiobutton_sem4");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, checkbutton_pdej, "checkbutton_pdej");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, comboboxentry_jour_modifier, "comboboxentry_jour_modifier");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, hseparator18, "hseparator18");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modifier_menu, "modifier_menu");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, image19, "image19");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, label23, "label23");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, actualiser_modifier, "actualiser_modifier");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, image21, "image21");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, label25, "label25");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, return_modifier_choix, "return_modifier_choix");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, image22, "image22");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, modif_remplire_case, "modif_remplire_case");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, image20, "image20");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, label24, "label24");
  GLADE_HOOKUP_OBJECT (n_modifier_choix, error_modifier_msg, "error_modifier_msg");

  return n_modifier_choix;
}

