/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_inscription (void);
GtkWidget* create_authen (void);
GtkWidget* create_Admin (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_chercher (void);
GtkWidget* create_fenetre_supprimer (void);
GtkWidget* create_update (void);
