/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *inscription;
  GtkWidget *authen;
  GtkWidget *Admin;
  GtkWidget *fenetre_afficher;
  GtkWidget *fenetre_ajout;
  GtkWidget *fenetre_modifier;
  GtkWidget *fenetre_chercher;
  GtkWidget *fenetre_supprimer;
	  GtkWidget *update;
    	  GtkWidget *image;
  GtkWidget *layout;
    



#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

 authen = create_authen ();

 chang_background(authen, 450, 500, "auth.jpeg");
 gtk_window_set_position(GTK_WINDOW(authen), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_widget_show (authen);
 




 /* inscription = create_inscription ();
  gtk_widget_show (inscription);

  Admin = create_Admin ();
  gtk_widget_show (Admin);
  fenetre_afficher = create_fenetre_afficher ();
  gtk_widget_show (fenetre_afficher);
  fenetre_ajout = create_fenetre_ajout ();
  gtk_widget_show (fenetre_ajout);
  update = create_update ();
  gtk_widget_show (update);
  fenetre_chercher = create_fenetre_chercher ();
  gtk_widget_show (fenetre_chercher);
 
  fenetre_supprimer=create_fenetre_supprimer();
  gtk_widget_show (fenetre_supprimer);*/

  gtk_main ();
  return 0;
}

